<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(DefaultTargetFrameworks);$(WindowsTarget)</TargetFrameworks>
        <Description>Shiny addon for all your push notification needs</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Core\Shiny.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(IsAndroidBuild)' == 'true'">
        <PackageReference Include="Xamarin.Android.Google.BillingClient" />
        <EmbeddedJar Include="Platforms\Android\native\amazon-appstore-sdk-3.0.7.jar" />
    </ItemGroup>
    
    <ItemGroup Condition="'$(IsWindowsBuild)' == 'true'">
        <PackageReference Include="Microsoft.WindowsAppSDK" />
    </ItemGroup>
    
</Project>